name: Check Packages
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Bootstrap monorepo
        run: npm run bootstrap:monorepo

      - name: Lint packages
        run: npm run lint

      - name: Build packages
        run: npm run build

      - name: Test packages
        run: npm run test